name: SARS-CoV-2_Omicron_spike_DMS
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - altair=4.2
  - altair_saver=0.5.0
  - biopython=1.79
  - entrez-direct=13.9
  - jupyterlab
  - jupyter_contrib_nbextensions
  - mafft=7.490
  - mamba
  - nbdime
  - nbstripout
  - nbsphinx
  - nbsphinx-link
  - nodejs
  - pandas=1.3.4
  - plotnine=0.8.0
  - python=3.8
  - pyyaml=6.0
  - scipy=1.7.1
  - snakemake=6.10.0
  - sphinx
  - treetime=0.8.2
  - upsetplot=0.6.0
  - usher=0.4.8
  - umi_tools=1.1.2
  - minimap2=2.23
  - pip
  - pip:
    - alignparse==0.3.0
    - dms-variants==1.3.0
